// src/sections/Hero.svelte
<script lang="ts">
	import { fade, fly } from "svelte/transition";
	import { onMount } from "svelte";
	let visible = false;

	// Observer to detect when the section is visible
	onMount(() => {
		const observer = new IntersectionObserver(
			(entries) => {
				if (entries[0].isIntersecting) {
					visible = true;
					observer.disconnect(); // Stop observing after it's visible
				}
			},
			{ threshold: 0.3 } // Trigger when 30% of Hero section is visible
		);

		const heroSection = document.getElementById("Hero");
		if (heroSection) observer.observe(heroSection);
	});

	function scrollToElement(id: string) {
		const element = document.getElementById(id);
		if (element) {
			element.scrollIntoView({ behavior: "smooth", block: "start" });
		} else {
			console.error("Element NOT found:", id);
		}
	}
</script>

<section id="Hero" class="relative min-h-screen flex flex-col items-center justify-center text-center px-6">
	{#if visible}
		<!-- Background Gradient -->
		<div
			in:fade={{ duration: 500 }}
			class="absolute inset-0 bg-gradient-to-r from-purple-800 via-blue-600 to-pink-500 opacity-40 -z-10"
		></div>

		<!-- Content -->
		<div class="grid grid-cols-1 md:grid-cols-2 gap-8 items-center max-w-6xl w-3/4 mx-auto">
			<!-- Left Side: Image & Name -->
			<div in:fly={{ x: -200, duration: 500 }} class="flex flex-col items-center space-y-4">
				<img
					src="/assets/avatars/hero.jpg"
					alt="Avatar Hero"
					loading="lazy"
					class="w-48 h-48 md:w-60 md:h-60 rounded-full border-4 border-primary shadow-lg"
				/>
				<code class="text-3xl md:text-4xl text-white font-semibold">John Doe</code>
			</div>

			<!-- Right Side: Text -->
			<blockquote in:fly={{ x: 200, duration: 500, delay: 500 }} class="text-4xl md:text-6xl font-bold text-theme text-left leading-tight">
				Lorem ipsum, dolor sit amet consectetur adipisicing elit.
			</blockquote>
		</div>

		<!-- Scroll Button (Fixed at Bottom) -->
		<div class="flex justify-center items-end w-full h-full absolute bottom-10" in:fly={{ y: 200, duration: 500, delay: 1000 }}>
			<button
				onclick={() => scrollToElement("WorkExperience")}
				class="btn"
			>
				View Projects
			</button>
		</div>
	{/if}
</section>

// src/components/sections/Hero.tsx
import React from "react";
import details from "../../data/details.json";
import CTAButtons from "../common/CTAButtons";

const Hero: React.FC = () => {
	return (
		<section
			id="home"
			className="min-h-screen flex items-center justify-center bg-gray-100 px-6 py-12"
		>
			<div className="container mx-auto flex flex-col md:flex-row items-center gap-8">
				{/* Left Content */}
				<div className="text-center md:text-left md:w-1/2 space-y-6">
					<h1 className="text-4xl font-extrabold text-gray-800 leading-tight">
						Hi, I'm{" "}
						<span className="text-blue-600">{details.personal.name}</span>
					</h1>
					<p className="text-lg text-gray-600">{details.personal.bio}</p>
					<CTAButtons />
				</div>

				{/* Right Image */}
				<div className="md:w-1/2 flex justify-center">
					<img
						src={
							details.personal.image || "/src/assets/images/default-avatar.jpg"
						}
						alt="Hero"
						className="w-80 h-80 md:w-full md:h-auto object-cover rounded-xl shadow-lg"
					/>
				</div>
			</div>
		</section>
	);
};

export default Hero;
