// src/components/Footer.jsx
import React from "react";
import { Link } from "react-router-dom";

const Footer = () => {
	return (
		<footer className="bg-gray-800 text-gray-300 py-6">
			<div className="container mx-auto flex flex-col md:flex-row justify-between items-center px-4">
				<p className="text-sm text-center md:text-left">
					&copy; {new Date().getFullYear()} My Portfolio. All rights reserved.
				</p>
				<nav className="flex space-x-4 mt-4 md:mt-0">
					<Link to="/" className="hover:text-white">
						Home
					</Link>
					<Link to="/#about" className="hover:text-white">
						About
					</Link>
					<Link to="/#projects" className="hover:text-white">
						Projects
					</Link>
					<Link to="/#contact" className="hover:text-white">
						Contact
					</Link>
				</nav>
			</div>
		</footer>
	);
};

export default Footer;

// src/components/Footer.svelte
<footer
	class="relative flex flex-col items-center justify-center text-center p-6 my-8 bg-primary"
>
	<p>&copy; {new Date().getFullYear()} DevPortfolio. All rights reserved.</p>
	<div class="flex justify-center mt-2 space-x-4">
		<a
			href="https://github.com/yourgithub"
			target="_blank"
			class="hover:text-gray-400">GitHub</a
		>
		<a
			href="https://linkedin.com/in/yourprofile"
			target="_blank"
			class="hover:text-gray-400">LinkedIn</a
		>
		<a href="mailto:your.email@example.com" class="hover:text-gray-400">Email</a
		>
	</div>
</footer>
