// src/components/layout/Footer.tsx
import React from "react";
import { Link } from "react-router-dom";
import details from "../../data/details.json";

const Footer: React.FC = () => {
	return (
		<footer className="w-full max-w-3xl mx-auto bg-gray-500/50 backdrop-blur-md shadow-lg shadow-blue-500/50 rounded-xl my-4">
			<div className="flex flex-col md:flex-row justify-between items-center py-4 px-6 text-white">
				{/* Copyright */}
				<p className="text-sm">
					&copy; {new Date().getFullYear()} {details.personal.name}
				</p>

				{/* Navigation Menu */}
				<nav>
					<ul className="flex space-x-5 text-sm font-bold">
						<li>
							<Link
								to="/"
								className="hover:text-blue-400 transition duration-200"
							>
								Home
							</Link>
						</li>
						<li>
							<Link
								to="/about"
								className="hover:text-blue-400 transition duration-200"
							>
								About
							</Link>
						</li>
						<li>
							<Link
								to="/projects"
								className="hover:text-blue-400 transition duration-200"
							>
								Projects
							</Link>
						</li>
						<li>
							<Link
								to="/contact"
								className="hover:text-blue-400 transition duration-200"
							>
								Contact
							</Link>
						</li>
					</ul>
				</nav>

				{/* Social Icons */}
				<div className="flex space-x-4">
					{Object.entries(details.socialMedia).map(([key, { url, icon }]) => (
						<a
							key={key}
							href={url}
							target="_blank"
							rel="noopener noreferrer"
							className="hover:opacity-75 transition duration-200"
						>
							<img src={icon} alt={key} className="w-6 h-6" />
						</a>
					))}
				</div>
			</div>
		</footer>
	);
};

export default Footer;

// src/components/Footer.svelte
<script lang="ts">
	import data from "../data/data.json";

	// Social links & sections from data.json
	const socialLinks = data.socialLinks;
	const sections = data.sections;

	// Smooth scroll function
	const scrollToSection = (id: string) => {
		const section = document.getElementById(id);
		if (section) {
			section.scrollIntoView({ behavior: "smooth", block: "start" });
		}
	};
</script>

<footer class="relative w-full py-10 bg-theme backdrop-blur-lg overflow-hidden">
	<!-- Footer Content -->
	<div
		class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center text-secondary"
	>
		<!-- Left Side: Logo & Copyright -->
		<div class="flex flex-col items-center md:items-start">
			<button
				on:click={() => scrollToSection("Hero")}
				class="flex items-center gap-3 group hover:scale-105 duration-350"
			>
				<img
					src="assets/logos/logo.svg"
					alt="Logo"
					class="w-10 h-10 rounded-full"
				/>
				<span
					class="text-xl font-bold text-[var(--accent-color)] group-hover:text-secondary transition"
					>{data.info.name}</span
				>
			</button>
			<p class="text-sm md:text-base font-medium mt-2 opacity-80">
				&copy; {new Date().getFullYear()}
				{data.info.name}. All rights reserved.
			</p>
		</div>

		<!-- Middle: Section Links -->
		<!-- Section Links -->
		<div class="flex flex-wrap justify-center gap-6 mt-6 md:mt-0">
			{#each sections.filter((section) => section.name !== "Home") as section}
				<button
					on:click={() => scrollToSection(section.id)}
					class="text-secondary hover:text-[var(--accent-color)] text-md font-medium duration-350 hover:scale-105 hover:font-extrabold"
				>
					{section.name}
				</button>
			{/each}
		</div>

		<!-- Right Side: Social Icons -->
		<div class="flex gap-4 mt-6 md:mt-0">
			{#each socialLinks as link}
				<a
					href={link.url}
					target="_blank"
					class="w-12 h-12 flex items-center justify-center rounded-full bg-white/10 backdrop-blur-md border border-white/20
					transition-all duration-350 hover:scale-125 hover:shadow-[0_0_15px_var(--accent-color)] hover:bg-[var(--accent-color)]"
				>
					<img
						src={link.icon}
						alt={link.name}
						class="w-7 h-7 transition-all duration-350 hover:invert"
					/>
				</a>
			{/each}
		</div>
	</div>
</footer>

<style>
	footer {
		scroll-snap-align: end;
	}
</style>
