// src/components/About.jsx
import React from "react";
import details from "../data/details.json";

const About = () => {
	return (
		<section id="about" className="py-16 bg-gray-100">
			<div className="container mx-auto px-6">
				<h2 className="text-4xl font-bold text-center text-gray-800 mb-12">
					About Me
				</h2>

				<div className="flex flex-col md:flex-row items-center justify-center gap-12">
					{/* Image Section */}
					<div className="w-64 h-64">
						<img
							src="/src/assets/images/profile.jpg"
							alt="About me"
							className="w-full h-full object-cover rounded-xl shadow-lg"
						/>
					</div>

					{/* Text Section */}
					<div className="max-w-2xl text-center md:text-left">
						<p className="text-lg text-gray-700 leading-relaxed">
							Hi, I'm{" "}
							<span className="font-semibold">{details.personal.name}</span>, a
							passionate web developer specializing in the MERN stack. I love
							building responsive, user-friendly websites and applications that
							solve real-world problems. With a strong focus on clean code and
							scalable architecture, I strive to create solutions that are both
							efficient and elegant.
						</p>
						<p className="text-lg text-gray-700 leading-relaxed mt-4">
							When I'm not coding, you can find me exploring new technologies,
							contributing to open-source projects, or reading about design
							patterns and best practices.
						</p>
					</div>
				</div>
			</div>
		</section>
	);
};

export default About;

// src/sections/About.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { fadeIn } from "../animations/gsap";
	import data from "../data/data.json";

	let aboutRef: HTMLElement;
	let cardsRef: HTMLElement[] = [];

	onMount(() => {
		fadeIn(aboutRef);
		cardsRef.forEach((el) => fadeIn(el));
	});

	let skills = Object.entries(data.skills).map(([title, icon]) => ({
		title,
		icon,
	}));
</script>

<section
	id="About"
	bind:this={aboutRef}
	class="section bg-theme text-theme py-20 px-6 md:px-12"
>
	<div class="max-w-6xl mx-auto flex flex-col md:flex-row items-start gap-12">
		<!-- Left Side: About Text -->
		<div class="md:w-1/2">
			<h2 class="text-5xl font-bold text-primary tracking-wide leading-tight">
				&lt; About Me /&gt;
			</h2>
			<p class="mt-6 text-lg text-secondary leading-relaxed">
				I'm a software engineer passionate about crafting high-quality,
				scalable, and efficient applications. I thrive on solving complex
				problems and designing user-centric interfaces that blend functionality
				with aesthetics.
			</p>
			<p class="mt-4 text-lg text-secondary leading-relaxed">
				With expertise in full-stack development, I enjoy creating seamless
				digital experiences using modern web technologies and interactive
				animations.
			</p>
		</div>

		<!-- Right Side: Skills Grid -->
		<div class="grid grid-cols-2 sm:grid-cols-3 gap-6 md:w-1/2">
			{#each skills as skill, i}
				<div
					bind:this={cardsRef[i]}
					class="relative bg-primary p-4 rounded-2xl shadow-lg flex flex-col items-center gap-3
					transition-all duration-300 hover:scale-105 hover:shadow-2xl transform hover:-translate-y-2"
				>
					<div
						class="relative w-16 h-16 flex items-center justify-center rounded-xl bg-white bg-opacity-10 shadow-md"
					>
						<img src={skill.icon} alt={skill.title} class="w-10 h-10" />
					</div>
					<h3
						class="text-lg font-semibold text-white text-center tracking-wide"
					>
						{skill.title}
					</h3>
					<div class="absolute inset-0 bg-white opacity-5 rounded-2xl"></div>
				</div>
			{/each}
		</div>
	</div>
</section>
