// src/components/Contact.jsx
import React, { useState } from "react";
import { db } from "../utils/firebase";
import { collection, addDoc, Timestamp } from "firebase/firestore";

const Contact = () => {
	const [formData, setFormData] = useState({
		name: "",
		email: "",
		message: "",
	});
	const [isSubmitting, setIsSubmitting] = useState(false);
	const [successMessage, setSuccessMessage] = useState("");
	const [errorMessage, setErrorMessage] = useState("");

	const handleChange = (e) => {
		const { name, value } = e.target;
		setFormData({ ...formData, [name]: value });
	};

	const handleSubmit = async (e) => {
		e.preventDefault();
		setIsSubmitting(true);
		setSuccessMessage("");
		setErrorMessage("");

		try {
			await addDoc(collection(db, "contacts"), {
				...formData,
				timestamp: Timestamp.now(),
			});
			setSuccessMessage("Message sent successfully!");
			setFormData({ name: "", email: "", message: "" });
		} catch (error) {
			setErrorMessage("Failed to send message. Please try again.");
			console.error(error);
		} finally {
			setIsSubmitting(false);
		}
	};

	return (
		<section id="contact" className="py-16 bg-gray-100">
			<div className="max-w-2xl mx-auto bg-white p-8 rounded-xl shadow-lg">
				<h2 className="text-3xl font-bold text-center text-gray-800 mb-6">
					Contact Me
				</h2>

				<form onSubmit={handleSubmit} className="space-y-6">
					{/* Name Input */}
					<div>
						<label htmlFor="name" className="block text-gray-700 font-medium">
							Name
						</label>
						<input
							type="text"
							id="name"
							name="name"
							value={formData.name}
							onChange={handleChange}
							required
							className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
						/>
					</div>

					{/* Email Input */}
					<div>
						<label htmlFor="email" className="block text-gray-700 font-medium">
							Email
						</label>
						<input
							type="email"
							id="email"
							name="email"
							value={formData.email}
							onChange={handleChange}
							required
							className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
						/>
					</div>

					{/* Message Input */}
					<div>
						<label
							htmlFor="message"
							className="block text-gray-700 font-medium"
						>
							Message
						</label>
						<textarea
							id="message"
							name="message"
							value={formData.message}
							onChange={handleChange}
							rows="5"
							required
							className="w-full px-4 py-3 rounded-lg border border-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-500"
						></textarea>
					</div>

					{/* Success & Error Messages */}
					{successMessage && (
						<p className="text-green-600 text-sm">{successMessage}</p>
					)}
					{errorMessage && (
						<p className="text-red-600 text-sm">{errorMessage}</p>
					)}

					{/* Submit Button */}
					<button
						type="submit"
						disabled={isSubmitting}
						className="w-full py-3 bg-indigo-600 text-white font-medium rounded-lg hover:bg-indigo-700 disabled:opacity-50 transition"
					>
						{isSubmitting ? "Sending..." : "Send Message"}
					</button>
				</form>
			</div>
		</section>
	);
};

export default Contact;

// src/sections/Contact.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { fadeIn } from "../animations/gsap";
	import { submitContactForm } from "../services/firebase";
	import { fly } from "svelte/transition";

	let contactRef: HTMLElement;
	let formRef: HTMLElement;
	let name = "";
	let email = "";
	let message = "";
	let successMessage = "";
	let errorMessage = "";
	let isSubmitting = false;

	onMount(() => {
		fadeIn(contactRef);
	});

	const handleSubmit = async () => {
		if (!name || !email || !message) {
			errorMessage = "All fields are required!";
			return;
		}

		isSubmitting = true;
		const response = await submitContactForm(name, email, message);
		isSubmitting = false;

		if (response.success) {
			successMessage = "Sent Successfully!";
			name = "";
			email = "";
			message = "";
		} else {
			errorMessage = "Failed to send message. Try again later!";
		}

		setTimeout(() => {
			successMessage = "";
			errorMessage = "";
		}, 3000);
	};
</script>

<section id="Contact" bind:this={contactRef} class="section relative py-24 px-6 md:px-12">
	<!-- Background Glow -->
	<div class="absolute inset-0 bg-gradient-to-br from-[var(--primary-color)] to-[var(--secondary-color)] opacity-15 blur-2xl -z-10"></div>

	<!-- Contact Header -->
	<div class="max-w-5xl mx-auto text-left">
		<h2 in:fly={{ x: -100, duration: 500 }}
			class="text-5xl font-extrabold tracking-wide bg-gradient-to-r from-[var(--primary-color)] via-[var(--accent-color)] to-[var(--secondary-color)] bg-clip-text text-transparent">
			&lt; Let's Connect /&gt;
		</h2>
		<p in:fly={{ x: -100, duration: 600 }}
			class="text-lg text-white/90 mt-4 max-w-2xl leading-relaxed">
			Have a project in mind or just want to say hi? Fill out the form below, and let’s create something amazing!
		</p>
	</div>

	<!-- Contact Form -->
	<div bind:this={formRef} in:fly={{ y: 100, duration: 600, delay: 300 }}
		class="mt-12 max-w-lg mx-auto bg-white/10 backdrop-blur-md p-8 rounded-2xl shadow-lg border border-white/20 animate-glow">
		
		<!-- Name Input -->
		<input type="text" bind:value={name} placeholder="Your Name"
			class="w-full px-4 py-3 border-2 border-white/50 bg-black/30 text-white/90 rounded-lg focus:outline-none 
			focus:border-[var(--accent-color)] transition duration-300 mb-4 placeholder-white/60" />

		<!-- Email Input -->
		<input type="email" bind:value={email} placeholder="Your Email"
			class="w-full px-4 py-3 border-2 border-white/50 bg-black/30 text-white/90 rounded-lg focus:outline-none 
			focus:border-[var(--accent-color)] transition duration-300 mb-4 placeholder-white/60" />

		<!-- Message Input -->
		<textarea bind:value={message} placeholder="Your Message"
			class="w-full px-4 py-3 border-2 border-white/50 bg-black/30 text-white/90 rounded-lg focus:outline-none 
			focus:border-[var(--accent-color)] transition duration-300 mb-4 h-32 placeholder-white/60"></textarea>

		<!-- Feedback Messages -->
		{#if successMessage}
			<p class="text-green-300">{successMessage}</p>
		{/if}
		{#if errorMessage}
			<p class="text-red-400">{errorMessage}</p>
		{/if}

		<!-- Submit Button -->
		<button on:click={handleSubmit} disabled={isSubmitting}
			class="btn w-full mt-4">
			{isSubmitting ? "Sending, Please Wait" : "Send Message"}
		</button>
	</div>
</section>
