// src/components/Projects.tsx
import React, { useEffect, useState } from "react";

interface Project {
	id: number;
	title: string;
	description: string;
	image: string;
	demoLink: string;
	codeLink: string;
}

const Projects: React.FC = () => {
	const [projects, setProjects] = useState<Project[]>([]);

	useEffect(() => {
		fetch("/src/data/projects.json")
			.then((response) => response.json())
			.then((data: Project[]) => setProjects(data))
			.catch((error) => console.error("Error fetching projects:", error));
	}, []);

	return (
		<section id="projects" className="py-16 bg-gray-100">
			<div className="container mx-auto px-6">
				<h2 className="text-4xl font-bold text-center text-gray-800 mb-12">
					My Projects
				</h2>

				<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
					{projects.map((project) => (
						<div
							key={project.id}
							className="bg-white rounded-lg shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300"
						>
							<img
								src={project.image}
								alt={project.title}
								className="w-full h-56 object-cover"
							/>
							<div className="p-6">
								<h3 className="text-xl font-semibold text-gray-800">
									{project.title}
								</h3>
								<p className="text-gray-600 mt-2">{project.description}</p>
								<div className="mt-4 flex space-x-4">
									<a
										href={project.demoLink}
										target="_blank"
										rel="noopener noreferrer"
										className="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition duration-300"
									>
										Live Demo
									</a>
									<a
										href={project.codeLink}
										target="_blank"
										rel="noopener noreferrer"
										className="bg-gray-700 text-white px-4 py-2 rounded-lg hover:bg-gray-800 transition duration-300"
									>
										Source Code
									</a>
								</div>
							</div>
						</div>
					))}
				</div>
			</div>
		</section>
	);
};

export default Projects;

// src/sections/Projects.svelte
<script lang="ts">
	import { onMount } from "svelte";
	import { applyTilt } from "../utils/tilt";
	import { fly } from "svelte/transition";
	import data from "../data/data.json";
	import { fadeIn } from "../animations/gsap";

	let projectRefs: HTMLElement[] = [];

	onMount(() => {
		projectRefs.forEach((el) => {
			// fadeIn(el);
			fly(el, { y: 500, duration: 500, delay: 1500 });
			applyTilt(el);
		});
	});
</script>

<section
	id="Projects"
	class="section bg-theme py-20 px-6 md:px-12"
>
		<div class="max-w-6xl mx-auto">
			<!-- Section Title -->
			<h2
				class="text-5xl font-bold text-accent tracking-wide text-left leading-tight"
			>
				&lt; Projects /&gt;
			</h2>
			<p class="mt-4 text-lg text-secondary max-w-2xl">
				Explore my latest projects that showcase my skills in building
				efficient, scalable, and visually stunning applications.
			</p>

			<!-- Project Grid -->
			<div class="mt-12 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
				{#each data.projects as project, i}
					<div
						bind:this={projectRefs[i]}
						
						class="relative bg-primary bg-opacity-10 backdrop-blur-md p-6 rounded-2xl shadow-lg border border-accent border-opacity-40
						hover:shadow-accent group"
					>
						<!-- Project Title -->
						<h3 class="text-2xl font-semibold text-secondary">
							{project.title}
						</h3>

						<!-- Description -->
						<p class="mt-3 text-md text-theme leading-relaxed">
							{project.description}
						</p>

						<!-- Buttons -->
						<div class="mt-6 flex gap-4">
							<a
								href={project.github}
								target="_blank"
								class="flex-1 text-center px-4 py-2 rounded-lg font-medium border border-secondary text-secondary
						transition-all duration-300 hover:bg-secondary hover:text-black"
							>
								GitHub
							</a>
							<a
								href={project.live}
								target="_blank"
								class="flex-1 text-center px-4 py-2 rounded-lg font-medium border border-accent text-accent
					transition-all duration-300 hover:bg-accent hover:text-black"
							>
								Live Demo
							</a>
						</div>
					</div>
				{/each}
			</div>
		</div>
</section>
